CREATE DATABASE MestreDb
USE MestreDb

CREATE TABLE Mestre 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(200) NOT NULL,
	Idade INT NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	Senha VARCHAR(200) NOT NULL
)

CREATE TABLE Capturas
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	IdMestre INT NOT NULL,
	IdPokemon INT NOT NULL,
	DataHora DATETIME NOT NULL,
	FOREIGN KEY (IdMestre) REFERENCES Mestre(Id)
)
